name: news_app_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-112.0.dev

dependencies:
  buttons_tabbar: ^1.3.13
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.14
  gap: ^3.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
